<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-E7OUSJFP" failures="1" tests="6" name="Regression" time="29.092" errors="0" timestamp="2024-08-08T00:56:50 EEST">
  <testcase classname="testCases.TC002_InValidRegister" name="registerExsitingCustomerTest" time="1.205"/>
  <testcase classname="testCases.TC004_InvalidPasswordLoginTest" name="LoginWithValidUserNameAndInvalidPasswordTest" time="1.012"/>
  <testcase classname="testCases.TC005_InvalidUserNameLoginTest" name="LoginWithValidUserNameAndInvalidPasswordTest" time="0.786"/>
  <testcase classname="testCases.TC007_DicountCodeTest" name="addDiscountCodeTest" time="4.969"/>
  <testcase classname="testCases.TC008_TermsOfServiceTest" name="verifyMandatoryTermsOfServiceTest" time="4.326"/>
  <testcase classname="testCases.TC009_BillingAdressMandatoryTest" name="verifyMandatoryTermsOfServiceTest" time="14.651">
    <failure type="java.lang.AssertionError" message="lists don&amp;apos;t have the same size expected [0] but found [5]">
      <![CDATA[java.lang.AssertionError: lists don't have the same size expected [0] but found [5]
at testCases.TC009_BillingAdressMandatoryTest.verifyMandatoryTermsOfServiceTest(TC009_BillingAdressMandatoryTest.java:46)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- verifyMandatoryTermsOfServiceTest -->
</testsuite> <!-- Regression -->
